### ISSUE TITLE
Doesn't work with .env

### ISSUE THREAD

**Issue by Sequoia** [ekmartin/check-env#4]
For the cli feature I added I realized I shot myself in the foot when using the `dotenv` module for local execution: env vars are loaded *after* startup, but startup fails.

I'd like to add a switch to the CLI that will read a .env if one is present and consider those variables as well when determining whether a variable is absent.

**Comment by ekmartin** [comment]
I think this might be a bit out of scope for this little project - sorry! Besides, if you're already requiring `dotenv` in code, why not just require `check-env` as well?
